```{contents}
```

# Selection, Indexing & Filtering

## Selection


### Column Selection

In [66]:
# Single column (Series)
loan_type = df['loan_type']

# Multiple columns (DataFrame)
df_subset = df[['application_id','loan_type','loan_amount_requested']]



---

### Row Selection by Position (`iloc`)

In [67]:
# First row
df.iloc[0]

# First 2 rows
df.iloc[0:2]

# Specific rows and columns
df.iloc[0:2, [0,3,4]]  # rows 0-1, columns application_id, loan_type, loan_amount_requested

                         application_id      loan_type  loan_amount_requested
0  c8bf0bea-70e6-4870-9125-41b8210c527f  Business Loan                 9999.0
1  91224cec-3544-4bc7-ac15-a9792da54c02       Car Loan               100000.0

---

#### Row Selection by Label (`loc`)

In [68]:
# Single row by index label
df.loc[0]

# Multiple rows & columns
df.loc[0:2, ['application_id','loan_type','loan_amount_requested']]

                         application_id       loan_type  loan_amount_requested
0  c8bf0bea-70e6-4870-9125-41b8210c527f   Business Loan                 9999.0
1  91224cec-3544-4bc7-ac15-a9792da54c02        Car Loan               100000.0
2  4efcd02d-4a03-4ab7-9bd1-0ff430493d0c  Education Loan               431000.0

---

#### Scalar Access

In [69]:

# Value at row 0, column 'loan_amount_requested'
df.at[0,'loan_amount_requested']

# Value by position
df.iat[0,4]

np.float64(9999.0)

---

#### Boolean Filtering

In [70]:

# Simple condition
high_loans = df[df['loan_amount_requested'] > 400000]

# Multiple conditions
approved_business = df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]

# Filter by multiple values
selected_loans = df[df['loan_type'].isin(['Car Loan','Education Loan'])]

# Filter using string methods
education_loans = df[df['loan_type'].str.contains('Education')]



---

#### Using `query()`

In [71]:
df.query("loan_amount_requested > 400000 and loan_status == 'Approved'")
df.query("loan_type in ['Car Loan','Education Loan']")

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
10,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,CUST101535,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,0265b56d-44bc-4342-a50b-0e298dd73063,CUST117199,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,c7e837fb-11b8-44d3-a093-45c899cfe38c,CUST115955,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN



---

## **8. Indexing with `.xs` (cross-section)**

In [72]:

# Set index to application_id
df_indexed = df.set_index('application_id')

# Select a row by index value
df_indexed.xs('c8bf0bea-70e6-4870-9125-41b8210c527f')

customer_id                                                         CUST109427
application_date                                                    2023-04-09
loan_type                                                        Business Loan
loan_amount_requested                                                   9999.0
loan_tenure_months                                                          12
interest_rate_offered                                                    11.66
purpose_of_loan                                              Medical Emergency
employment_status                                                      Retired
monthly_income                                                         34700.0
cibil_score                                                                714
existing_emis_monthly                                                   1100.0
debt_to_income_ratio                                                      3.17
property_ownership_status                                               Rented
residential_address          94/31, Sehgal Zila, Vadodara-380521, Anantapur...
applicant_age                                                               28
gender                                                                  Female
number_of_dependents                                                         3
loan_status                                                           Approved
fraud_flag                                                                   0
fraud_type                                                                 NaN
Name: c8bf0bea-70e6-4870-9125-41b8210c527f, dtype: object


**Summary**

| Method                 | Example                                                                    | Notes                   |
| ---------------------- | -------------------------------------------------------------------------- | ----------------------- |
| Column selection       | `df['loan_type']`, `df[['loan_type','loan_amount_requested']]`             | Single/multiple columns |
| Row selection (`iloc`) | `df.iloc[0:2]`                                                             | By position             |
| Row selection (`loc`)  | `df.loc[0:2,['loan_type','loan_amount_requested']]`                        | By label                |
| Scalar access          | `df.at[0,'loan_amount_requested']`, `df.iat[0,4]`                          | Single value            |
| Boolean filter         | `df[df['loan_amount_requested']>400000]`                                   | Condition(s)            |
| Multiple conditions    | `df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]` | & / \|                  |
| `.isin()`              | `df[df['loan_type'].isin(['Car Loan','Education Loan'])]`                  | Membership test         |
| String filter          | `df[df['loan_type'].str.contains('Education')]`                            | `.str` accessor         |
| Query                  | `df.query("loan_amount_requested>400000")`                                 | SQL-like syntax         |
| `.xs`                  | `df_indexed.xs('c8bf0bea-70e6-4870-9125-41b8210c527f')`                    | Cross-section of index  |


## Indexing 

### Basic Indexing

#### Column selection

In [73]:

# Single column as Series
df['loan_type']

# Multiple columns as DataFrame
df[['loan_type','loan_amount_requested']]

            loan_type  loan_amount_requested
0       Business Loan                 9999.0
1            Car Loan               100000.0
2      Education Loan               431000.0
3            Car Loan               324000.0
4       Personal Loan               100000.0
...               ...                    ...
49995  Education Loan               381000.0
49996  Education Loan               736000.0
49997        Car Loan               436000.0
49998   Business Loan               827000.0
49999       Home Loan               100000.0

[50000 rows x 2 columns]



---

#### Row selection by position (`iloc`)

In [74]:

# Single row
df.iloc[0]

# Multiple rows
df.iloc[0:2]

# Specific rows and columns
df.iloc[0:2, [0,3,4]]  # rows 0-1, columns: application_id, loan_type, loan_amount_requested

                         application_id      loan_type  loan_amount_requested
0  c8bf0bea-70e6-4870-9125-41b8210c527f  Business Loan                 9999.0
1  91224cec-3544-4bc7-ac15-a9792da54c02       Car Loan               100000.0



---

#### Row selection by label (`loc`)

In [75]:
# Single row by index label
df.loc[0]

# Rows and columns
df.loc[0:2, ['application_id','loan_type','loan_amount_requested']]

                         application_id       loan_type  loan_amount_requested
0  c8bf0bea-70e6-4870-9125-41b8210c527f   Business Loan                 9999.0
1  91224cec-3544-4bc7-ac15-a9792da54c02        Car Loan               100000.0
2  4efcd02d-4a03-4ab7-9bd1-0ff430493d0c  Education Loan               431000.0



---

#### Scalar access

In [76]:

# By label
df.at[0,'loan_amount_requested']

# By position
df.iat[0,4]

np.float64(9999.0)



---

#### Boolean indexing

In [77]:

# Simple condition
df[df['loan_amount_requested'] > 400000]

# Multiple conditions
df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]

# Using `.isin()`
df[df['loan_type'].isin(['Car Loan','Education Loan'])]

# Using string methods
df[df['loan_type'].str.contains('Education')]

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
10,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,CUST101535,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
13,d4460e0d-0d9d-448a-8a78-dfa169b1816d,CUST116366,2024-04-12,Education Loan,100000.0,120,12.25,Wedding,Student,75400.0,...,4100.0,5.44,Jointly Owned,"045, Sanghvi Nagar, Sangli-Miraj & Kupwad 6170...",33,Female,3,Declined,0,NaN
14,973a866a-a7bd-4166-8121-a1e220e29a83,CUST103082,2023-12-16,Education Loan,737000.0,240,7.00,Medical Emergency,Retired,10000.0,...,5500.0,55.00,Jointly Owned,"H.No. 88, Dube Nagar, Nanded 255803, Khammam, ...",28,Male,2,Approved,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49975,61500afa-7f09-4e27-89e2-db2053bfb73e,CUST110102,2023-07-21,Education Loan,744000.0,360,11.16,Medical Emergency,Self-Employed,10000.0,...,4400.0,44.00,Rented,"20/36, Manne Circle, Raurkela Industrial Towns...",32,Other,4,Declined,0,NaN
49977,bca9b62a-7eb2-4230-aea3-c67fa3c9e77a,CUST109084,2023-09-16,Education Loan,612000.0,360,9.75,Medical Emergency,Unemployed,84400.0,...,3800.0,4.50,Jointly Owned,"70, Batta Chowk, Fatehpur 548114, Rewa, Assam,...",27,Other,3,Declined,0,NaN
49980,b6713cf7-4674-4c32-a0ed-1ee832d8e2c1,CUST116930,2024-03-10,Education Loan,517000.0,12,9.66,Debt Consolidation,Salaried,58700.0,...,5800.0,9.88,Jointly Owned,"20/52, Manda Path, Deoghar-478030, Gorakhpur, ...",45,Female,4,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN



---

#### Using `query()`

In [78]:
df.query("loan_amount_requested > 400000 and loan_status == 'Approved'")
df.query("loan_type in ['Car Loan','Education Loan']")

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
10,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,CUST101535,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,0265b56d-44bc-4342-a50b-0e298dd73063,CUST117199,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,c7e837fb-11b8-44d3-a093-45c899cfe38c,CUST115955,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN



---

#### `.xs()` - cross-section

In [79]:
# Set index to application_id
df_indexed = df.set_index('application_id')

# Select a row by index
df_indexed.xs('c8bf0bea-70e6-4870-9125-41b8210c527f')

customer_id                                                         CUST109427
application_date                                                    2023-04-09
loan_type                                                        Business Loan
loan_amount_requested                                                   9999.0
loan_tenure_months                                                          12
interest_rate_offered                                                    11.66
purpose_of_loan                                              Medical Emergency
employment_status                                                      Retired
monthly_income                                                         34700.0
cibil_score                                                                714
existing_emis_monthly                                                   1100.0
debt_to_income_ratio                                                      3.17
property_ownership_status                                               Rented
residential_address          94/31, Sehgal Zila, Vadodara-380521, Anantapur...
applicant_age                                                               28
gender                                                                  Female
number_of_dependents                                                         3
loan_status                                                           Approved
fraud_flag                                                                   0
fraud_type                                                                 NaN
Name: c8bf0bea-70e6-4870-9125-41b8210c527f, dtype: object



---

#### `.iloc` with slicing & boolean

In [80]:

# First 2 rows and specific columns
df.iloc[0:2, 3:5]

# Rows where age > 40 and columns loan_type, loan_amount_requested
df.loc[df['applicant_age']>40, ['loan_type','loan_amount_requested']]

            loan_type  loan_amount_requested
1            Car Loan               100000.0
2      Education Loan               431000.0
4       Personal Loan               100000.0
6       Personal Loan               220000.0
8       Personal Loan               106000.0
...               ...                    ...
49995  Education Loan               381000.0
49996  Education Loan               736000.0
49997        Car Loan               436000.0
49998   Business Loan               827000.0
49999       Home Loan               100000.0

[27857 rows x 2 columns]



---

### `.loc` with callable

In [81]:
# Use a callable for dynamic selection
df.loc[lambda x: x['loan_amount_requested']>400000, ['loan_type','loan_amount_requested']]

            loan_type  loan_amount_requested
2      Education Loan               431000.0
5       Business Loan              1164000.0
7           Home Loan               475000.0
9           Home Loan               768000.0
12     Education Loan               745000.0
...               ...                    ...
49993        Car Loan               587000.0
49994        Car Loan               606000.0
49996  Education Loan               736000.0
49997        Car Loan               436000.0
49998   Business Loan               827000.0

[31718 rows x 2 columns]



---

### Multi-indexing / hierarchical indexing (example)

In [82]:
df_multi = df.set_index(['loan_type','loan_status'])
df_multi.loc[('Business Loan','Approved')]

C:\Users\sangouda\AppData\Local\Temp\ipykernel_16488\2413433408.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  df_multi.loc[('Business Loan','Approved')]

                                                 application_id customer_id  \
loan_type     loan_status
Business Loan Approved     c8bf0bea-70e6-4870-9125-41b8210c527f  CUST109427
              Approved     d91cf990-efa1-44ad-94bf-44e6c79d1051  CUST116153
              Approved     8b5ac393-e374-43d2-a746-ff3ff81be55f  CUST104446
              Approved     ed49abd8-e898-4dbc-9215-1514b7a39d09  CUST113497
              Approved     a6911b40-1664-4632-9063-18f7c11f684b  CUST119301
...                                                         ...         ...
              Approved     88b42b2e-e6f3-4ba9-8737-cf47c8f117da  CUST119905
              Approved     e9dace7a-80a1-4661-9252-3200ea144471  CUST102724
              Approved     ca596b7d-e039-43b4-8a89-5492487d0392  CUST117078
              Approved     128a19d8-b00f-42d8-9712-39d29c63df2f  CUST115453
              Approved     46a8f901-8005-4ae7-923e-f9d0dc8e0ae8  CUST109088

                          application_date  loan_amount_requested  \
loan_type     loan_status
Business Loan Approved          2023-04-09                 9999.0
              Approved          2025-02-19              1164000.0
              Approved          2023-12-20               823000.0
              Approved          2025-01-04               911000.0
              Approved          2023-12-12               460000.0
...                                    ...                    ...
              Approved          2024-08-06               783000.0
              Approved          2025-05-16               942000.0
              Approved          2024-11-22               633000.0
              Approved          2022-12-26               849000.0
              Approved          2022-12-16               827000.0

                           loan_tenure_months  interest_rate_offered  \
loan_type     loan_status
Business Loan Approved                     12                  11.66
              Approved                     24                   9.83
              Approved                    240                  10.58
              Approved                     60                  12.73
              Approved                     36                  10.02
...                                       ...                    ...
              Approved                    240                   9.91
              Approved                     24                  11.11
              Approved                     60                  12.28
              Approved                     36                   8.73
              Approved                     24                  16.18

                              purpose_of_loan employment_status  \
loan_type     loan_status
Business Loan Approved      Medical Emergency           Retired
              Approved                Wedding     Self-Employed
              Approved              Education     Self-Employed
              Approved                Wedding     Self-Employed
              Approved                Wedding    Business Owner
...                                       ...               ...
              Approved     Business Expansion        Unemployed
              Approved       Vehicle Purchase           Retired
              Approved      Medical Emergency          Salaried
              Approved        Home Renovation     Self-Employed
              Approved       Vehicle Purchase    Business Owner

                           monthly_income  cibil_score  existing_emis_monthly  \
loan_type     loan_status
Business Loan Approved            34700.0          714                 1100.0
              Approved            72700.0          710                 3300.0
              Approved            28000.0          770                10200.0
              Approved            82200.0          661                 6300.0
              Approved            75000.0          750                 3500.0
...                                   ...          ...                    ...
              Approved            10600.0          677                 7100.0
              Approved            99100.0          678                 1500.0
              Approved            42600.0          671                 5600.0
              Approved            70900.0          694                 3400.0
              Approved            46700.0          759                 8100.0

                           debt_to_income_ratio property_ownership_status  \
loan_type     loan_status
Business Loan Approved                     3.17                    Rented
              Approved                     4.54             Jointly Owned
              Approved                    36.43                    Rented
              Approved                     7.66             Jointly Owned
              Approved                     4.67             Jointly Owned
...                                         ...                       ...
              Approved                    66.98                     Owned
              Approved                     1.51             Jointly Owned
              Approved                    13.15             Jointly Owned
              Approved                     4.80             Jointly Owned
              Approved                    17.34                    Rented

                                                         residential_address  \
loan_type     loan_status
Business Loan Approved     94/31, Sehgal Zila, Vadodara-380521, Anantapur...
              Approved     977, Sami Nagar, Jalgaon-061357, Giridih, Assa...
              Approved     96/618, Comar Nagar, Bhopal 306490, Dibrugarh,...
              Approved     13/81, Kamdar Zila, Ghaziabad-656287, Bally, U...
              Approved     371, Rout Marg, Navi Mumbai 096789, Motihari, ...
...                                                                      ...
              Approved     27/261, Amble Street, Dehri-622504, Etawah, Ka...
              Approved     67, Ahuja Chowk, Ongole-796728, Panihati, Maha...
              Approved     69/474, Tiwari Ganj, Dibrugarh-918142, Waranga...
              Approved     H.No. 02, Bhasin Road, Bhusawal-302234, Shimla...
              Approved     H.No. 697, Sathe Road, Ongole 444116, Satna, A...

                           applicant_age  gender  number_of_dependents  \
loan_type     loan_status
Business Loan Approved                28  Female                     3
              Approved                25    Male                     4
              Approved                31    Male                     3
              Approved                63  Female                     0
              Approved                37   Other                     2
...                                  ...     ...                   ...
              Approved                32   Other                     3
              Approved                63    Male                     1
              Approved                34    Male                     2
              Approved                24   Other                     3
              Approved                62   Other                     3

                           fraud_flag fraud_type
loan_type     loan_status
Business Loan Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN
...                               ...        ...
              Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN
              Approved              0        NaN

[8123 rows x 19 columns]



---

**Summary of Indexing Methods**

| Method                 | Example                                                                    | Use case              |
| ---------------------- | -------------------------------------------------------------------------- | --------------------- |
| Column selection       | `df['loan_type']`                                                          | Single column         |
| Multiple columns       | `df[['loan_type','loan_amount_requested']]`                                | Subset of columns     |
| Row selection (`iloc`) | `df.iloc[0:2]`                                                             | By position           |
| Row selection (`loc`)  | `df.loc[0:2, ['loan_type','loan_amount_requested']]`                       | By label              |
| Scalar access          | `df.at[0,'loan_amount_requested']` / `df.iat[0,4]`                         | Single value          |
| Boolean filter         | `df[df['loan_amount_requested']>400000]`                                   | Conditional selection |
| Multiple conditions    | `df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]` | Complex filters       |
| `.isin()`              | `df[df['loan_type'].isin(['Car Loan','Education Loan'])]`                  | Membership            |
| String filter          | `df[df['loan_type'].str.contains('Education')]`                            | String matching       |
| Query                  | `df.query("loan_amount_requested>400000")`                                 | SQL-like syntax       |
| Cross-section          | `df_indexed.xs('id')`                                                      | Select row from index |
| Multi-index            | `df_multi.loc[('Business Loan','Approved')]`                               | Hierarchical indexing |

## Filtering


### Boolean Filtering

You create a **boolean condition** and use it to filter rows.

In [83]:

# Rows where loan_amount_requested > 400000
df[df['loan_amount_requested'] > 400000]

# Multiple conditions: logical AND (&) / OR (|)
df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]
df[(df['loan_type']=='Car Loan') | (df['loan_status']=='Declined')]

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
4,a8d1639e-170b-41b2-826a-55c7dae38d16,CUST112319,2023-11-20,Personal Loan,100000.0,36,14.14,Business Expansion,Salaried,43900.0,...,1100.0,2.51,Rented,"85/24, Bali Zila, Sambalpur 922071, Tumkur, Ke...",50,Other,0,Declined,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
13,d4460e0d-0d9d-448a-8a78-dfa169b1816d,CUST116366,2024-04-12,Education Loan,100000.0,120,12.25,Wedding,Student,75400.0,...,4100.0,5.44,Jointly Owned,"045, Sanghvi Nagar, Sangli-Miraj & Kupwad 6170...",33,Female,3,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49990,5e493549-e51f-4bea-b3e6-2eb109b7f8e0,CUST110116,2024-09-29,Car Loan,374000.0,24,13.18,Wedding,Unemployed,61100.0,...,7400.0,12.11,Jointly Owned,"H.No. 87, Lanka Ganj, Eluru-653884, Burhanpur,...",52,Male,1,Approved,0,NaN
49992,f3408e3d-6a4e-4904-8e90-8ac79d410ee4,CUST104103,2023-08-24,Car Loan,361000.0,120,7.84,Education,Business Owner,72200.0,...,6500.0,9.00,Rented,"42, Khatri Chowk, Dindigul-721412, Nagpur, Goa...",64,Other,2,Approved,0,NaN
49993,0265b56d-44bc-4342-a50b-0e298dd73063,CUST117199,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,c7e837fb-11b8-44d3-a093-45c899cfe38c,CUST115955,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN



---

### `.isin()` Filtering

Filter rows where a column matches a list of values.

In [84]:
# Rows with specific loan types
df[df['loan_type'].isin(['Car Loan', 'Education Loan'])]

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
10,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,CUST101535,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,0265b56d-44bc-4342-a50b-0e298dd73063,CUST117199,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,c7e837fb-11b8-44d3-a093-45c899cfe38c,CUST115955,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN



---

### String Filtering (`.str` accessor)

Filter based on **string patterns** in a column.


# Rows where loan_type contains 'Education'
df[df['loan_type'].str.contains('Education')]

# Rows where employment_status starts with 'S'
df[df['employment_status'].str.startswith('S')]



---

### Filtering with `.query()`

Filter using a **SQL-like string expression**.

In [85]:
# Using query to filter
df.query("loan_amount_requested > 400000 and loan_status == 'Approved'")

# Filter multiple values
df.query("loan_type in ['Car Loan','Education Loan']")

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
10,2cdc104f-abbf-4f8d-b9c1-2e073ed17bb7,CUST101535,2024-10-19,Education Loan,395000.0,12,8.33,Debt Consolidation,Salaried,10100.0,...,0.0,0.00,Jointly Owned,"46/02, Buch Zila, Chinsurah-642812, Buxar, Miz...",40,Male,4,Approved,0,NaN
12,e0b509dc-5357-427d-bd69-681308a68efc,CUST106264,2024-08-31,Education Loan,745000.0,12,9.78,Debt Consolidation,Self-Employed,35000.0,...,0.0,0.00,Rented,"H.No. 75, Contractor Ganj, Bhiwandi-559674, Si...",61,Female,1,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49993,0265b56d-44bc-4342-a50b-0e298dd73063,CUST117199,2024-10-20,Car Loan,587000.0,24,9.03,Medical Emergency,Business Owner,50700.0,...,400.0,0.79,Owned,"H.No. 59, Mangal Road, Nagercoil-198543, Kanpu...",33,Other,3,Approved,0,NaN
49994,c7e837fb-11b8-44d3-a093-45c899cfe38c,CUST115955,2023-11-22,Car Loan,606000.0,120,9.73,Medical Emergency,Student,65700.0,...,3400.0,5.18,Rented,"H.No. 35, Rajan Street, Ichalkaranji 261561, A...",30,Female,0,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN



---

### Filtering on Index

If a column is set as index, you can filter with `.loc`:

In [86]:

df_indexed = df.set_index('application_id')

# Filter by index label
df_indexed.loc[['c8bf0bea-70e6-4870-9125-41b8210c527f','91224cec-3544-4bc7-ac15-a9792da54c02']]

,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,cibil_score,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
application_id,,,,,,,,,,,,,,,,,,,,
c8bf0bea-70e6-4870-9125-41b8210c527f,CUST109427,2023-04-09,Business Loan,9999.0,12,11.66,Medical Emergency,Retired,34700.0,714,1100.0,3.17,Rented,"94/31, Sehgal Zila, Vadodara-380521, Anantapur...",28,Female,3,Approved,0,NaN
91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,667,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN



---

### Filtering with `.between()`

Filter rows where a numeric column is within a range.

In [87]:
# Rows with loan_amount_requested between 100000 and 500000
df[df['loan_amount_requested'].between(100000, 500000)]

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
4,a8d1639e-170b-41b2-826a-55c7dae38d16,CUST112319,2023-11-20,Personal Loan,100000.0,36,14.14,Business Expansion,Salaried,43900.0,...,1100.0,2.51,Rented,"85/24, Bali Zila, Sambalpur 922071, Tumkur, Ke...",50,Other,0,Declined,0,NaN
6,cd837d7e-98de-4d26-8b6f-f59d7bef9d2a,CUST118841,2023-02-02,Personal Loan,220000.0,36,8.71,Vehicle Purchase,Unemployed,47300.0,...,6700.0,14.16,Rented,"805, Bhakta Path, Thiruvananthapuram-330918, K...",46,Male,1,Approved,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49990,5e493549-e51f-4bea-b3e6-2eb109b7f8e0,CUST110116,2024-09-29,Car Loan,374000.0,24,13.18,Wedding,Unemployed,61100.0,...,7400.0,12.11,Jointly Owned,"H.No. 87, Lanka Ganj, Eluru-653884, Burhanpur,...",52,Male,1,Approved,0,NaN
49992,f3408e3d-6a4e-4904-8e90-8ac79d410ee4,CUST104103,2023-08-24,Car Loan,361000.0,120,7.84,Education,Business Owner,72200.0,...,6500.0,9.00,Rented,"42, Khatri Chowk, Dindigul-721412, Nagpur, Goa...",64,Other,2,Approved,0,NaN
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN
49999,6aaf792e-6755-408e-a9ef-4d9bf841864b,CUST113445,2025-03-25,Home Loan,100000.0,24,9.44,Education,Business Owner,83600.0,...,2200.0,2.63,Owned,"23/178, Iyengar Chowk, Karawal Nagar-908829, J...",46,Male,3,Approved,0,NaN



---

### Filtering Missing / Non-Missing Data

In [88]:

# Rows with missing values
df[df['loan_status'].isnull()]

# Rows without missing values
df[df['loan_status'].notnull()]

,application_id,customer_id,application_date,loan_type,loan_amount_requested,loan_tenure_months,interest_rate_offered,purpose_of_loan,employment_status,monthly_income,...,existing_emis_monthly,debt_to_income_ratio,property_ownership_status,residential_address,applicant_age,gender,number_of_dependents,loan_status,fraud_flag,fraud_type
0,c8bf0bea-70e6-4870-9125-41b8210c527f,CUST109427,2023-04-09,Business Loan,9999.0,12,11.66,Medical Emergency,Retired,34700.0,...,1100.0,3.17,Rented,"94/31, Sehgal Zila, Vadodara-380521, Anantapur...",28,Female,3,Approved,0,NaN
1,91224cec-3544-4bc7-ac15-a9792da54c02,CUST106146,2023-09-23,Car Loan,100000.0,240,13.62,Education,Unemployed,51600.0,...,0.0,0.00,Owned,"H.No. 00, Sheth Chowk, Ichalkaranji 006728, Im...",44,Other,3,Approved,0,NaN
2,4efcd02d-4a03-4ab7-9bd1-0ff430493d0c,CUST100674,2023-05-22,Education Loan,431000.0,60,11.40,Medical Emergency,Self-Employed,14800.0,...,4600.0,31.08,Rented,"H.No. 81, Dutta Path, Kozhikode-340301, Tadepa...",56,Other,4,Approved,0,NaN
3,a61337d4-ba04-4a68-b492-2cb8266e6ed7,CUST106466,2024-07-09,Car Loan,324000.0,120,10.36,Debt Consolidation,Self-Employed,28800.0,...,4000.0,13.89,Rented,"H.No. 022, Rege Road, Tiruvottiyur-927857, Aur...",27,Other,4,Declined,0,NaN
4,a8d1639e-170b-41b2-826a-55c7dae38d16,CUST112319,2023-11-20,Personal Loan,100000.0,36,14.14,Business Expansion,Salaried,43900.0,...,1100.0,2.51,Rented,"85/24, Bali Zila, Sambalpur 922071, Tumkur, Ke...",50,Other,0,Declined,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,1d4b1017-e8a1-4a7b-94d1-63e90b05d665,CUST114840,2024-12-29,Education Loan,381000.0,24,12.05,Vehicle Purchase,Student,49200.0,...,2400.0,4.88,Rented,"28, Rana Path, Gorakhpur-411614, Tirupati, Mah...",55,Other,3,Approved,0,NaN
49996,2984426c-6d0b-437c-9a13-84bf3244c6d4,CUST103055,2022-06-17,Education Loan,736000.0,120,11.03,Medical Emergency,Student,28600.0,...,4000.0,13.99,Jointly Owned,"20/836, Varma Zila, Udaipur-879473, Rajkot, We...",61,Other,0,Approved,0,NaN
49997,cdbc7ad8-0f23-46c4-aaca-619053ad5605,CUST119886,2024-12-14,Car Loan,436000.0,12,10.98,Wedding,Student,42000.0,...,600.0,1.43,Jointly Owned,"H.No. 505, Luthra Zila, Panchkula 991795, Kolh...",48,Other,4,Approved,0,NaN
49998,46a8f901-8005-4ae7-923e-f9d0dc8e0ae8,CUST109088,2022-12-16,Business Loan,827000.0,24,16.18,Vehicle Purchase,Business Owner,46700.0,...,8100.0,17.34,Rented,"H.No. 697, Sathe Road, Ongole 444116, Satna, A...",62,Other,3,Approved,0,NaN
49999,6aaf792e-6755-408e-a9ef-4d9bf841864b,CUST113445,2025-03-25,Home Loan,100000.0,24,9.44,Education,Business Owner,83600.0,...,2200.0,2.63,Owned,"23/178, Iyengar Chowk, Karawal Nagar-908829, J...",46,Male,3,Approved,0,NaN



---

**Summary**

| Method                     | Example                                                                    | Use Case                     |
| -------------------------- | -------------------------------------------------------------------------- | ---------------------------- |
| Boolean                    | `df[df['loan_amount_requested'] > 400000]`                                 | Simple condition             |
| Multiple conditions        | `df[(df['loan_type']=='Business Loan') & (df['loan_status']=='Approved')]` | Complex filters              |
| `.isin()`                  | `df[df['loan_type'].isin(['Car Loan','Education Loan'])]`                  | Membership test              |
| String filter              | `df[df['loan_type'].str.contains('Education')]`                            | Text-based filter            |
| `.query()`                 | `df.query("loan_amount_requested>400000")`                                 | SQL-like syntax              |
| Index filter               | `df_indexed.loc[['id1','id2']]`                                            | Filter by index              |
| `.between()`               | `df[df['loan_amount_requested'].between(100000,500000)]`                   | Range-based filter           |
| `.isnull()` / `.notnull()` | `df[df['loan_status'].isnull()]`                                           | Filter missing / non-missing |